// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ePizzaHub.BusinessLogic.Data;

#nullable disable

namespace ePizzaHub.BusinessLogic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624124839_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ePizzaHub.Models.CartItemModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<string>("f_customer_session_uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<Guid>("f_pizza_uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("f_quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.HasIndex("f_pizza_uid");

                    b.ToTable("t_cart_item", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.CouponModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("f_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<decimal>("f_discount_percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("f_expiry_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_active")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<decimal>("f_max_discount_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(6);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.ToTable("t_coupon", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.OrderItemModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<Guid>("f_order_uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<Guid>("f_pizza_uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<int>("f_quantity")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<decimal>("f_unit_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(5);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.HasIndex("f_order_uid");

                    b.HasIndex("f_pizza_uid");

                    b.ToTable("t_order_item", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.OrderModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("f_contact_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<string>("f_customer_user_uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<string>("f_delivery_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_paid")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("f_order_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<decimal>("f_total_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(7);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.ToTable("t_order", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.PaymentMethodModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_active")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<string>("f_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.ToTable("t_payment_method", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.PaymentModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("f_amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<Guid>("f_order_uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<Guid>("f_payment_method_uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<string>("f_payment_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("f_transaction_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.HasIndex("f_order_uid");

                    b.HasIndex("f_payment_method_uid");

                    b.ToTable("t_payment", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.PizzaCategoryModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_active")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<string>("f_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.ToTable("t_pizza_category", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.PizzaModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("f_category_uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<string>("f_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<string>("f_image_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<bool>("f_is_available")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("f_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<decimal>("f_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(7);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.HasIndex("f_category_uid");

                    b.ToTable("t_pizza", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.RoleModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_active")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<string>("f_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.ToTable("t_role", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.TaxSettingModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_active")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<decimal>("f_percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(3);

                    b.Property<string>("f_tax_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.ToTable("t_tax_setting", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.UserAddressModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("f_address_line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("f_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_default")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<string>("f_postal_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.Property<Guid>("f_user_iid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(6);

                    b.HasKey("f_uid");

                    b.HasIndex("f_user_iid");

                    b.ToTable("t_user_address", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.UserModel", b =>
                {
                    b.Property<Guid>("f_uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("f_create_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(101);

                    b.Property<DateTime?>("f_create_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(100);

                    b.Property<Guid?>("f_delete_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(105);

                    b.Property<DateTime?>("f_delete_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(104);

                    b.Property<string>("f_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("f_fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<int>("f_iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_iid"));

                    b.Property<bool>("f_is_active")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<string>("f_lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("f_password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(6);

                    b.Property<string>("f_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(7);

                    b.Property<Guid>("f_role_uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(8);

                    b.Property<Guid?>("f_update_by")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(103);

                    b.Property<DateTime?>("f_update_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(102);

                    b.HasKey("f_uid");

                    b.HasIndex("f_role_uid");

                    b.ToTable("t_user", (string)null);
                });

            modelBuilder.Entity("ePizzaHub.Models.CartItemModel", b =>
                {
                    b.HasOne("ePizzaHub.Models.PizzaModel", "f_pizza")
                        .WithMany()
                        .HasForeignKey("f_pizza_uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("f_pizza");
                });

            modelBuilder.Entity("ePizzaHub.Models.OrderItemModel", b =>
                {
                    b.HasOne("ePizzaHub.Models.OrderModel", "f_order")
                        .WithMany("f_order_items")
                        .HasForeignKey("f_order_uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePizzaHub.Models.PizzaModel", "f_pizza")
                        .WithMany()
                        .HasForeignKey("f_pizza_uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("f_order");

                    b.Navigation("f_pizza");
                });

            modelBuilder.Entity("ePizzaHub.Models.PaymentModel", b =>
                {
                    b.HasOne("ePizzaHub.Models.OrderModel", "f_order")
                        .WithMany()
                        .HasForeignKey("f_order_uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ePizzaHub.Models.PaymentMethodModel", "f_payment_method")
                        .WithMany()
                        .HasForeignKey("f_payment_method_uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("f_order");

                    b.Navigation("f_payment_method");
                });

            modelBuilder.Entity("ePizzaHub.Models.PizzaModel", b =>
                {
                    b.HasOne("ePizzaHub.Models.PizzaCategoryModel", "f_category")
                        .WithMany()
                        .HasForeignKey("f_category_uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("f_category");
                });

            modelBuilder.Entity("ePizzaHub.Models.UserAddressModel", b =>
                {
                    b.HasOne("ePizzaHub.Models.UserModel", "f_user")
                        .WithMany()
                        .HasForeignKey("f_user_iid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("f_user");
                });

            modelBuilder.Entity("ePizzaHub.Models.UserModel", b =>
                {
                    b.HasOne("ePizzaHub.Models.RoleModel", "f_role")
                        .WithMany()
                        .HasForeignKey("f_role_uid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("f_role");
                });

            modelBuilder.Entity("ePizzaHub.Models.OrderModel", b =>
                {
                    b.Navigation("f_order_items");
                });
#pragma warning restore 612, 618
        }
    }
}
